### ISSUE TITLE
YAML frontmatter variables - clarify

### ISSUE THREAD

**Issue by r0bis** [thingsym/hugo-theme-techdoc#70]
Dear @thingsym ,

Thank you very much for the excellent theme. I like it a lot. I have a few questions about the markdown file YAML header variables in the sample site. Is there a place where they are documented? If not I would be very happy to do so.

```YAML
TableOfContents: true
# inserts the current page's TOC
``` 
but what do the following do:
```YAML
showPagination: false
# what is the expected effect?
next: /tutorials/github-pages-blog
prev: /tutorials/automated-deployments
# previous and next at the bottom of the page seem to appear automatically anyhow
images: 
  - images/pexels-photo-196666.jpeg
# is it supposed to be individual page's header image?
```
I would also be happy to document what other variables specific to this theme are possible.
 
Many thanks,
Roberts
